### ISSUE TITLE
failed to extract capabilities al-khaser_x86.exe_ 

### ISSUE THREAD

**Issue by mr-tz** [mandiant/capa#1081]
```
 failed to extract capabilities: reference WMI statements /home/runner/work/capa-rules/capa-rules/scripts/../tests/data/al-khaser_x86.exe_ 
Traceback (most recent call last):
  File "/home/runner/work/capa-rules/capa-rules/scripts/lint.py", line 362, in check_rule
    capabilities = get_sample_capabilities(ctx, path)
  File "/home/runner/work/capa-rules/capa-rules/scripts/lint.py", line 321, in get_sample_capabilities
    capabilities, _ = capa.main.find_capabilities(ctx.rules, extractor, disable_progress=True)
  File "/home/runner/work/capa-rules/capa-rules/capa/main.py", line 269, in find_capabilities
    function_matches, bb_matches, insn_matches, feature_count = find_code_capabilities(ruleset, extractor, f)
  File "/home/runner/work/capa-rules/capa-rules/capa/main.py", line 197, in find_code_capabilities
    features, bmatches, imatches = find_basic_block_capabilities(ruleset, extractor, fh, bb)
  File "/home/runner/work/capa-rules/capa-rules/capa/main.py", line 153, in find_basic_block_capabilities
    ifeatures, imatches = find_instruction_capabilities(ruleset, extractor, f, bb, insn)
  File "/home/runner/work/capa-rules/capa-rules/capa/main.py", line 120, in find_instruction_capabilities
    for feature, addr in itertools.chain(
  File "/home/runner/work/capa-rules/capa-rules/capa/features/extractors/viv/extractor.py", line 73, in extract_insn_features
    yield from capa.features.extractors.viv.insn.extract_features(fh, bbh, ih)
  File "/home/runner/work/capa-rules/capa-rules/capa/features/extractors/viv/insn.py", line 701, in extract_features
    for feature, addr in insn_handler(f, bb, insn):
  File "/home/runner/work/capa-rules/capa-rules/capa/features/extractors/viv/insn.py", line 505, in extract_function_calls_from
    yield Characteristic("calls from"), AbsoluteVirtualAddress(target)
  File "/home/runner/work/capa-rules/capa-rules/capa/features/address.py", line 31, in __new__
    assert v >= 0
AssertionError
```

**Comment by mr-tz** [comment]
example: 
```asm
.text:00449D27 E8 58 C3 55 8B    call    near ptr 8B9A6084h
```
