### ISSUE TITLE
IDA plugin: match namespace

### ISSUE THREAD

**Issue by mr-tz** [mandiant/capa#1090]
See https://github.com/mandiant/capa/commit/269f056e523d3602a22255a9d9a41bcff3c59522#diff-ad19852bd00d29871509fd7b8ec453853aba42528c2b28da78f9c60a87526b9aR598-R601

Rendering matched namespaces is not supported

### Steps to Reproduce

PMA 17-02.dll
Run IDA plugin

```
ERROR:capa.ida.plugin.form:Failed to render results (error: 'host-interaction/file-system/read')
Traceback (most recent call last):
  File "\capa\capa\ida\plugin\form.py", line 825, in load_capa_results
    self.model_data.render_capa_doc(self.doc, self.view_show_results_by_function.isChecked())
  File "\capa\capa\ida\plugin\model.py", line 510, in render_capa_doc
    self.render_capa_doc_by_program(doc)
  File "\capa\capa\ida\plugin\model.py", line 497, in render_capa_doc_by_program
    self.render_capa_doc_match(parent2, match, doc)
  File "\capa\capa\ida\plugin\model.py", line 441, in render_capa_doc_match
    self.render_capa_doc_match(parent2, child, doc)
  File "\capa\capa\ida\plugin\model.py", line 434, in render_capa_doc_match
    parent2 = self.render_capa_doc_feature_node(
  File "\capa\capa\ida\plugin\model.py", line 553, in render_capa_doc_feature_node
    parent2 = self.render_capa_doc_feature(
  File "\capa\capa\ida\plugin\model.py", line 604, in render_capa_doc_feature
    return CapaExplorerRuleMatchItem(parent, display, source=doc.rules[matched_rule_name].source)
KeyError: 'host-interaction/file-system/read'
```

**Comment by mike-hunhoff** [comment]
see #1091
