### ISSUE TITLE
vverbose: AttributeError: 'OperandNumberFeature' object has no attribute 'operand number'

### ISSUE THREAD

**Issue by mr-tz** [mandiant/capa#1151]
Reach out to Jae for the sample.

```
capa.exe -vv sample.exe
loading : 100%|████████████████████████████████████████████████████████████████| 703/703 [00:00<00:00, 1802.60 rules/s]
matching: 100%|█████████████████████████| 227/227 [00:02<00:00, 84.60 functions/s, skipped 136 library functions (59%)]
Traceback (most recent call last):
  File "main.py", line 1197, in <module>
  File "main.py", line 1133, in main
  File "render\vverbose.py", line 358, in render
  File "render\vverbose.py", line 351, in render_vverbose
  File "render\vverbose.py", line 338, in render_rules
  File "render\vverbose.py", line 232, in render_match
  File "render\vverbose.py", line 232, in render_match
  File "render\vverbose.py", line 232, in render_match
  [Previous line repeated 2 more times]
  File "render\vverbose.py", line 229, in render_match
  File "render\vverbose.py", line 184, in render_node
  File "render\vverbose.py", line 137, in render_feature
AttributeError: 'OperandNumberFeature' object has no attribute 'operand number'
[2528] Failed to execute script 'main' due to unhandled exception!
```

**Comment by raw-data** [comment]
@mike-hunhoff just a heads-up, it seams that the issue persists within the IDA plugin, testing `cape_explorer.py` with the latest rules set, the same error is triggered in `capa.ida.plugin.model.py` as reported below

```
ERROR:capa.ida.plugin.form:Failed to render results (error: 'OperandNumberFeature' object has no attribute 'operand number')

lib\site-packages\capa\ida\plugin\model.py", line 523, in capa_doc_feature_to_display
    value = getattr(feature, feature.type)
AttributeError: 'OperandNumberFeature' object has no attribute 'operand number'
INFO:capa.ida.plugin.form:Analysis failed.
```
calling `capa` instead from _CLI_ (`capa.exe -vv sample.exe`), now works as expected after the pushed fix.
