### ISSUE TITLE
Error running capa on `IDA`

### ISSUE THREAD

**Issue by r0ny123** [mandiant/capa#1154]
### Description

Got the following error:
```
ERROR:capa.ida.plugin.form:Failed to render results (error: unexpected rule scope: Scope.INSTRUCTION)
Traceback (most recent call last):
  File "C:\Users\Rony\AppData\Local\Programs\Python\Python39\lib\site-packages\capa\ida\plugin\form.py", line 825, in load_capa_results
    self.model_data.render_capa_doc(self.doc, self.view_show_results_by_function.isChecked())
  File "C:\Users\Rony\AppData\Local\Programs\Python\Python39\lib\site-packages\capa\ida\plugin\model.py", line 512, in render_capa_doc
    self.render_capa_doc_by_program(doc)
  File "C:\Users\Rony\AppData\Local\Programs\Python\Python39\lib\site-packages\capa\ida\plugin\model.py", line 497, in render_capa_doc_by_program
    raise RuntimeError("unexpected rule scope: " + str(rule.meta.scope))
RuntimeError: unexpected rule scope: Scope.INSTRUCTION
INFO:capa.ida.plugin.form:Analysis failed.
```

### Steps to Reproduce

1. Load any binary in `IDA`.
2. Run `capa explorer` plugin
3. Get the following error :
See `description`

**Expected behavior:**

Capa should render the results correctly and display the result in `IDA`.

**Actual behavior:**

See `description`

### Versions

`capa 4.0.1`
`IDA Pro 7.6`
`Python 3.9`

**Comment by doomedraven** [comment]
[latest capa_explorer.py from](https://raw.githubusercontent.com/mandiant/capa/master/capa/ida/plugin/capa_explorer.py)
capa 4.0.1
IDA pro 8
python 3.9 
<img width="729" alt="Screenshot 2022-08-21 at 09 29 58" src="https://user-images.githubusercontent.com/1856495/185780569-9b368d91-5b9e-4fd3-a9ba-6d0a7fa7c063.png">

**Comment by doomedraven** [comment]
ok with any sample no, only with specific. Guys i will share problematic sample with you in private

```
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for RuleMetadata
examples
  none is not an allowed value (type=type_error.none.not_allowed)
INFO:capa.ida.plugin.form:Analysis failed.
```

**Comment by mr-tz** [comment]
I cannot reproduce this in IDA 7.7 with a sample @doomedraven provide.
Can you share a sample to test with?

**Comment by doomedraven** [comment]
@mr-tz that is his sample

**Comment by mr-tz** [comment]
Ah, ok, thanks :)
@r0ny123 Can you retry with the most recent code?

**Comment by r0ny123** [comment]
Yeah I did with latest rules and capa 4.0.1 but no luck. (Only with the sample shared privately by @doomedraven).

**Comment by mr-tz** [comment]
Hm... have you updated the plugin code also?

**Comment by mr-tz** [comment]
Got it. I see the error using IDA 7.6. Will investigate.

**Comment by mr-tz** [comment]
So IDA 7.6 didn't recognize the library code which resulted in a Instruction scope match which we missed to update in the IDA plugin.

**Comment by mr-tz** [comment]
Does the fix work for you?

**Comment by r0ny123** [comment]
No. The capa plugin failed to load. Got the following error:

```
C:\Program Files\IDA Pro 7.6\plugins\capa_explorer.py: cannot import name 'CapaExplorerDataModel' from 'capa.ida.plugin.model' (C:\Users\Rony\AppData\Local\Programs\Python\Python39\lib\site-packages\capa\ida\plugin\model.py)
Traceback (most recent call last):
  File "C:\Program Files\IDA Pro 7.6\python\3\ida_idaapi.py", line 616, in IDAPython_ExecScript
    exec(code, g)
  File "C:/Program Files/IDA Pro 7.6/plugins/capa_explorer.py", line 9, in <module>
    from capa.ida.plugin import CapaExplorerPlugin
  File "C:\Users\Rony\AppData\Local\Programs\Python\Python39\lib\site-packages\capa\ida\plugin\__init__.py", line 13, in <module>
    from capa.ida.plugin.form import CapaExplorerForm
  File "C:\Users\Rony\AppData\Local\Programs\Python\Python39\lib\site-packages\capa\ida\plugin\form.py", line 32, in <module>
    from capa.ida.plugin.view import (
  File "C:\Users\Rony\AppData\Local\Programs\Python\Python39\lib\site-packages\capa\ida\plugin\view.py", line 22, in <module>
    from capa.ida.plugin.model import CapaExplorerDataModel
ImportError: cannot import name 'CapaExplorerDataModel' from 'capa.ida.plugin.model' (C:\Users\Rony\AppData\Local\Programs\Python\Python39\lib\site-packages\capa\ida\plugin\model.py)
```

**Comment by mr-tz** [comment]
Does your `model.py` not contain `CapaExplorerDataModel`?

**Comment by r0ny123** [comment]
Ah, just double-checked. It worked. Thanks for the quick fixes @mr-tz, as always.
