### ISSUE TITLE
AssertionError in capa.features.address

### ISSUE THREAD

**Issue by gdesmar** [mandiant/capa#1177]
### Description
Analyzing sample [7765e7d6c11b8db158f7ed70aa33a6c0935cd5c2c282304ed89a7695f7925abb](https://www.virustotal.com/gui/file/7765e7d6c11b8db158f7ed70aa33a6c0935cd5c2c282304ed89a7695f7925abb) raise an exception.

### Steps to Reproduce
```bash
$ wget https://github.com/mandiant/capa/releases/download/v4.0.1/capa-v4.0.1-linux.zip
$ unzip capa-v4.0.1-linux.zip
$ ./capa 7765e7d6c11b8db158f7ed70aa33a6c0935cd5c2c282304ed89a7695f7925abb
loading : 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 703/703 [00:00<00:00, 1650.65 rules/s]
matching:  92%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎          | 1056/1145 [00:33<00:02, 31.76 functions/s, skipped 34 library functions (2%)]
Traceback (most recent call last):
  File "main.py", line 1197, in <module>
  File "main.py", line 1120, in main
  File "main.py", line 270, in find_capabilities
  File "main.py", line 198, in find_code_capabilities
  File "main.py", line 154, in find_basic_block_capabilities
  File "main.py", line 121, in find_instruction_capabilities
  File "features/extractors/viv/extractor.py", line 73, in extract_insn_features
  File "features/extractors/viv/insn.py", line 702, in extract_features
  File "features/extractors/viv/insn.py", line 512, in extract_function_calls_from
  File "features/address.py", line 31, in __new__
AssertionError
[184031] Failed to execute script 'main' due to unhandled exception!
```

The specific line looks to be in capa.features.address.AbsoluteVirtualAddress : `assert v >= 0` in the `__new__` function.

### Expected behavior
I was expecting the error to be caught/handled, and the result to show the other things it found (assuming it did find other things).
Maybe see an item in the output related to the corrupted/un-handled data.

### Versions
capa v4.0.1-0-g3c41415
Ubuntu 20.04

### Additional Information
Hopefully you have access to download the file from VirusTotal. If not, I can probably download it, zip it with a password and upload it here.

**Comment by mr-tz** [comment]
First off, nice profile picture 🙃

I'm able to reproduce the error on the provided file. I think the issue is that data gets analyzed as code and happens to produce a negative offset which we assert against (hence your error). We'll address this and see if we can improve the error handling as well as the code analysis part.
