### ISSUE TITLE
AttributeError: OperandNumberFeature

### ISSUE THREAD

**Issue by williballenthin** [mandiant/capa#1211]
```
ERROR:capa.ida.plugin.form:Failed to render results (error: 'OperandNumberFeature' object has no attribute 'operand number')
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\site-packages\capa\ida\plugin\form.py", line 825, in load_capa_results
    self.model_data.render_capa_doc(self.doc, self.view_show_results_by_function.isChecked())
  File "C:\Program Files\Python38\lib\site-packages\capa\ida\plugin\model.py", line 512, in render_capa_doc
    self.render_capa_doc_by_program(doc)
  File "C:\Program Files\Python38\lib\site-packages\capa\ida\plugin\model.py", line 499, in render_capa_doc_by_program
    self.render_capa_doc_match(parent2, match, doc)
  File "C:\Program Files\Python38\lib\site-packages\capa\ida\plugin\model.py", line 441, in render_capa_doc_match
    self.render_capa_doc_match(parent2, child, doc)
  File "C:\Program Files\Python38\lib\site-packages\capa\ida\plugin\model.py", line 441, in render_capa_doc_match
    self.render_capa_doc_match(parent2, child, doc)
  File "C:\Program Files\Python38\lib\site-packages\capa\ida\plugin\model.py", line 441, in render_capa_doc_match
    self.render_capa_doc_match(parent2, child, doc)
  [Previous line repeated 2 more times]
  File "C:\Program Files\Python38\lib\site-packages\capa\ida\plugin\model.py", line 434, in render_capa_doc_match
    parent2 = self.render_capa_doc_feature_node(
  File "C:\Program Files\Python38\lib\site-packages\capa\ida\plugin\model.py", line 551, in render_capa_doc_feature_node
    display = self.capa_doc_feature_to_display(feature)
  File "C:\Program Files\Python38\lib\site-packages\capa\ida\plugin\model.py", line 523, in capa_doc_feature_to_display
    value = getattr(feature, feature.type)
AttributeError: 'OperandNumberFeature' object has no attribute 'operand number'
INFO:capa.ida.plugin.form:Analysis failed.
```

"Using latest Capa v4 and rules inside IDA 8.1"

**Comment by williballenthin** [comment]
this is a duplicate of #1151 and fixed in #1176
