### ISSUE TITLE
capa explorer: unit test fails

### ISSUE THREAD

**Issue by mike-hunhoff** [mandiant/capa#1243]
capa v4.0.1

```
FAIL mimikatz-function=0x4011FB-offset(-0x1)-True
Traceback (most recent call last):
  File "C:/Exclusions/capa-4.0.1/tests/test_ida_features.py", line 61, in test_ida_features
    fixtures.do_test_feature_presence(get_ida_extractor, sample, scope, feature, expected)
  File "C:\Exclusions/capa-4.0.1/tests\fixtures.py", line 792, in do_test_feature_presence
    assert feature.evaluate(features) == expected, msg
AssertionError: offset(-0x1) should be found in function=0x4011FB
FAIL mimikatz-function=0x4011FB-offset(-0x2)-True
Traceback (most recent call last):
  File "C:/Exclusions/capa-4.0.1/tests/test_ida_features.py", line 61, in test_ida_features
    fixtures.do_test_feature_presence(get_ida_extractor, sample, scope, feature, expected)
  File "C:\Exclusions/capa-4.0.1/tests\fixtures.py", line 792, in do_test_feature_presence
    assert feature.evaluate(features) == expected, msg
AssertionError: offset(-0x2) should be found in function=0x4011FB
```

**Comment by mike-hunhoff** [comment]
IDA appears to be treating offset as 64-bit two's complement e.g.

```
movsx   eax, word ptr [edi-4]
```

emits

```
0xfffffffffffffffc
```

we assume displacement is 32-bit two's complement so we fail to generate the correct negative.

tested IDA >= 8.0

**Comment by mike-hunhoff** [comment]
we grab the displacement from `idaapi.op_t.addr` here: https://github.com/mandiant/capa/blob/e6585ee526eea970ca0d378645ac4789f628a93e/capa/features/extractors/ida/helpers.py#L224

`idaapi.op_t.addr` docs: https://www.hex-rays.com/products/ida/support/sdkdoc/classop__t.html#acaaeff517df0b7156b4b8521a3900cdc

**Comment by mike-hunhoff** [comment]
Displacement is 32-bit in 32-bit IDA. I'm guessing `ea_t` is 32-bit in 32-bit IDA and 64-bit in 64-bit IDA and because `ea_t` is used for displacement the displacement is 64-bit (even though we expect it only ever be 32-bit).

<img width="913" alt="Screen Shot 2022-12-27 at 5 26 50 PM" src="https://user-images.githubusercontent.com/42192796/209739228-30915d5b-eb89-4275-9b72-380e11d6b108.png">

<img width="369" alt="Screen Shot 2022-12-27 at 5 26 43 PM" src="https://user-images.githubusercontent.com/42192796/209739229-4cba985b-b483-475d-8bf0-b0f407b85fa5.png">

**Comment by mike-hunhoff** [comment]
IDA >= 8.2 is 64-bit only so we can expect this issue to persist. We assume 32-bit displacement based on discussions [here](https://stackoverflow.com/questions/31853189/x86-64-assembly-why-displacement-not-64-bits) so we can simply mask the offset.
