### ISSUE TITLE
Cannot run capa from IDA Pro 7.7

### ISSUE THREAD

**Issue by Pl0414141** [mandiant/capa#1252]
1. installed capa via pip
2. Created python script to run IDA plugin
3. Version 4 of capa rules
4. Python version 3.8

```
ERROR:capa.ida.plugin.form:Failed to render results (error: unexpected rule scope: Scope.INSTRUCTION)
Traceback (most recent call last):
  File "C:\Users\mar\AppData\Local\Programs\Python\Python38\lib\site-packages\capa\ida\plugin\form.py", line 825, in load_capa_results
    self.model_data.render_capa_doc(self.doc, self.view_show_results_by_function.isChecked())
  File "C:\Users\mar\AppData\Local\Programs\Python\Python38\lib\site-packages\capa\ida\plugin\model.py", line 512, in render_capa_doc
    self.render_capa_doc_by_program(doc)
  File "C:\Users\mar\AppData\Local\Programs\Python\Python38\lib\site-packages\capa\ida\plugin\model.py", line 497, in render_capa_doc_by_program
    raise RuntimeError("unexpected rule scope: " + str(rule.meta.scope))
RuntimeError: unexpected rule scope: Scope.INSTRUCTION
INFO:capa.ida.plugin.form:Analysis failed.
```

**Comment by williballenthin** [comment]
> Version 4 of capa rules

would you please clarify how you downloaded the rules at version four? we're currently trying to improve our documentation to avoid issues like this and i'd like to double check that its working.

this looks like a version mismatch problem (maybe capa v3 with rules v4). what version of capa do you have installed?

**Comment by mr-tz** [comment]
this may be similar to #1154 or was just fixed this week (unreleased), can you please try again and/or provide additional information?

**Comment by mr-tz** [comment]
Please reopen if this issue still exists and additional information is available.
