### ISSUE TITLE
explorer: unhandled exception when Alt+F5 used and plugin already opened

### ISSUE THREAD

**Issue by mike-hunhoff** [mandiant/capa#1345]
To recreate, open plugin and then use Alt + F5. Prompt appears to "load existing" or "reanalyze". Selecting either results in the following exception:
 
```
Failed while executing plugin_t.run():
Traceback (most recent call last):
  File "C:\Users\spring\AppData\Local\Programs\Python\Python310\lib\site-packages\capa\ida\plugin\__init__.py", line 70, in run
    self.form = CapaExplorerForm(self.PLUGIN_NAME, arg)
  File "C:\Users\spring\AppData\Local\Programs\Python\Python310\lib\site-packages\capa\ida\plugin\form.py", line 233, in __init__
    self.analyze_program(analyze=analyze)
  File "C:\Users\spring\AppData\Local\Programs\Python\Python310\lib\site-packages\capa\ida\plugin\form.py", line 897, in analyze_program
    self.range_model_proxy.invalidate()
AttributeError: 'CapaExplorerForm' object has no attribute 'range_model_proxy'
```
It appears IDA creates new `CapaExplorerForm` which calls `CapaExplorerForm.__init__` which calls `CapaExplorerForm.Show`. `CapaExplorerForm.OnCreate` is not called because a plugin form already exists so nothing gets initialized resulting in the exception.

**Comment by mr-tz** [comment]
Great, I'll assign you. Do you have access to IDA Pro with IDAPython scripting support?

**Comment by manasghandat** [comment]
No i dont have the access

**Comment by mr-tz** [comment]
Hm, this is going hard to test/debug then 😞 
Maybe you can support on a different issue instead?

**Comment by manasghandat** [comment]
Can you suggest any other issues ?

**Comment by mr-tz** [comment]
#1303 or #1051 (capa explorer related but doesn't require IDA) come to mind, happy to take another look if these don't fit or interest you

**Comment by HongThatCong** [comment]
I fix temporary:
\capa\capa\ida\plugin\__init__.py
![image](https://user-images.githubusercontent.com/67528122/224197843-29c4151e-7dac-49b4-a27b-2050da8b02d1.png)

**Comment by williballenthin** [comment]
closed in #1395

**Comment by williballenthin** [comment]
thank you @HongThatCong !
