### ISSUE TITLE
CAPE report key "static" may not be present

### ISSUE THREAD

**Issue by williballenthin** [mandiant/capa#1700]
77c961050aa252d6d595ec5120981abf02068c968f4a5be5958d10e87aa6f0e8 from v2.2 archive in #1698 is v2.2 but doesn't have "static":

```
@williballenthin ➜ /workspaces/capa (dynamic-feature-extraction) $ python -m capa.main -r rules1 tests/data/dynamic/cape/v2.2/77c961050aa252d6d595ec5120981abf02068c968f4a5be5958d10e87aa6f0e8.json
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/workspaces/capa/capa/main.py", line 1655, in <module>
    sys.exit(main())
  File "/workspaces/capa/capa/main.py", line 1506, in main
    file_extractors = get_file_extractors(args.sample, format_)
  File "/workspaces/capa/capa/main.py", line 830, in get_file_extractors
    file_extractors.append(capa.features.extractors.cape.extractor.CapeExtractor.from_report(report))
  File "/workspaces/capa/capa/features/extractors/cape/extractor.py", line 85, in from_report
    static = report["static"]
KeyError: 'static'
```

this sample doesn't have an API trace, either. we'll want to recognize that and let the user know what to do.

  - [ ] fix handling, warn user
  - [ ] add test file for this case
  - [ ] add test for this case

**Comment by williballenthin** [comment]
see #1701 for v2.4 support
