### ISSUE TITLE
elf: ValueError: symbol name not found

### ISSUE THREAD

**Issue by mike-hunhoff** [mandiant/capa#1704]
`libyvr.so` from https://www.virustotal.com/gui/file/4261cc05a8c4ecaf1605ef931397a4d97cc12fe38738a4f6016c3695aa2c571f/detection

```
> python -m capa.main --os linux  -r rules libyvr.so
Traceback (most recent call last):
  File "C:\Users\spring\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\spring\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Exclusions\capa\capa\main.py", line 1345, in <module>
    sys.exit(main())
  File "C:\Exclusions\capa\capa\main.py", line 1275, in main
    capabilities, counts = find_capabilities(rules, extractor, disable_progress=args.quiet)
  File "C:\Exclusions\capa\capa\main.py", line 283, in find_capabilities
    function_matches, bb_matches, insn_matches, feature_count = find_code_capabilities(
  File "C:\Exclusions\capa\capa\main.py", line 210, in find_code_capabilities
    features, bmatches, imatches = find_basic_block_capabilities(ruleset, extractor, fh, bb)
  File "C:\Exclusions\capa\capa\main.py", line 166, in find_basic_block_capabilities
    ifeatures, imatches = find_instruction_capabilities(ruleset, extractor, f, bb, insn)
  File "C:\Exclusions\capa\capa\main.py", line 133, in find_instruction_capabilities
    for feature, addr in itertools.chain(
  File "C:\Exclusions\capa\capa\features\extractors\viv\extractor.py", line 77, in extract_insn_features
    yield from capa.features.extractors.viv.insn.extract_features(fh, bbh, ih)
  File "C:\Exclusions\capa\capa\features\extractors\viv\insn.py", line 737, in extract_features
    for feature, addr in insn_handler(f, bb, insn):
  File "C:\Exclusions\capa\capa\features\extractors\viv\insn.py", line 125, in extract_insn_api_features
    sym_name = symtab.get_name(symbol)
  File "C:\Exclusions\capa\capa\features\extractors\elf.py", line 702, in get_name
    raise ValueError("symbol name not found")
ValueError: symbol name not found
```

**Comment by williballenthin** [comment]
`lib/x86_64/libyvr.so`. not present in the `x86` build.

**Comment by williballenthin** [comment]
```
ipdb> symbol
Symbol(name_offset=57184, value=8589934599, size=0, info=0, other=0, shndx=0)
ipdb> hex(symbol.name_offset)
'0xdf60'
ipdb> hex(len(self.strtab.buf))
'0x450'
```

doesn't seem like the symtab is long enough.

**Comment by williballenthin** [comment]
```
ipdb> hex(symbol.value)
'0x200000007'
```
