### ISSUE TITLE
Cannot use capa in cmd after installing flare-capa by pip

### ISSUE THREAD

**Issue by mikroice90** [mandiant/capa#1781]
Good morning,

I was using capa since I've first installed Flare VM few years ago.
Yesterday I realised I can improve my IDA analysis by adding capa explorer as plugin to IDA Pro.

I finally made it with well written documentation, but today when I wanted to use `capa -vv sample.exe`
 in my command line i realised that it did not work. 
I get this errors:
`ERROR:capa:default embedded rules not found! (maybe you installed capa as a library?)
ERROR:capa:provide your own rule set via the `-r` option.`

I downloaded rules from github and tried to use it with ` -r ` flag but unfortunately i get different errors
```
ERROR:capa:Using default signature path, but it doesn't exist. Please install the signatures first: https://github.com/m
andiant/capa/blob/master/doc/installation.md#method-2-using-capa-as-a-python-library.
Traceback (most recent call last):
  File "c:\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python37\Scripts\capa.exe\__main__.py", line 7, in <module>
  File "c:\python37\lib\site-packages\capa\main.py", line 1097, in main
    ret = handle_common_args(args)
  File "c:\python37\lib\site-packages\capa\main.py", line 1047, in handle_common_args
    raise IOError(f"signatures path {sigs_path} does not exist or cannot be accessed")
OSError: signatures path c:\python37\lib\site-packages\capa\..\sigs does not exist or cannot be accessed
```

I would like to use both:
1) capa in cmd or poweshell (with rules and signatures in defaults paths)
2) flare-capa as python plugin to use it in IDA Pro as plugin

To use capa in cmd or in powershell i needed to uninstall flare-capa using pip.
After this change capa start working.

I did not found any helpful information on github issues or in google search.

I used:
1) capa 5.1.0,
2) IDA Pro 8.2
3) Python 3.7.9

I will be gratefull for any help.

**Comment by mr-tz** [comment]
closing due to inactivity, please reopen if needed

**Comment by fr0gger** [comment]
I haven't looked into it much, but a quick fix is to create an empty 'sigs' folder in the site-package folder, right here: `Python\PythonXXX\Lib\site-packages\sigs`. 

Capa keeps checking for this 'sigs' folder multiple times in the `main.py` script and using the absolute path doesn't change anything. Hope it helps :)
