### ISSUE TITLE
Bad Memory Access causes capa script/binary to fail and exit

### ISSUE THREAD

**Issue by KotEnot17** [mandiant/capa#1859]
When analyzing ELF files. Error appears on windows executable versions above 3.0 (Tested: 4.0, 5.0 and 6.1) Version 3.0 work as intended 
![image](https://github.com/mandiant/capa/assets/151056170/52ce7ecf-2ddc-4ed6-919f-7774509e3ae3)

**Comment by KotEnot17** [comment]
Traceback (most recent call last):
  File "main.py", line 1197, in <module>
  File "main.py", line 1105, in main
  File "main.py", line 536, in get_extractor
  File "main.py", line 474, in get_workspace
  File "viv_utils\__init__.py", line 117, in getWorkspace
  File "vivisect\__init__.py", line 2786, in loadFromFile
  File "vivisect\parsers\elf.py", line 31, in parseFile
  File "vivisect\parsers\elf.py", line 532, in loadElfIntoWorkspace
  File "envi\memory.py", line 206, in readMemoryPtr
  File "envi\memory.py", line 188, in readMemValue
  File "envi\memory.py", line 581, in readMemory
envi.exc.SegmentationViolation: SegmentationViolation('Bad Memory Read (invalid memory address): 0x0: 0x8')
[45124] Failed to execute script 'main' due to unhandled exception!

**Comment by mr-tz** [comment]
Can you please share a sample where you encounter this? The ELF samples I've tested and that our CI uses seem to work fine.

**Comment by williballenthin** [comment]
according to the stack trace, this is a bug in vivisect, but we can still work with upstream to get it patched, if we can identify the source.
