### ISSUE TITLE
PyQt -  ImportError: DLL load failed while importing sip: The specified module could not be found.

### ISSUE THREAD

**Issue by AVman1** [mandiant/capa#681]
```
C:\Program Files\IDA Pro 7.5 SP3\plugins\capa_explorer.py: DLL load failed while importing sip: The specified module could not be found.
Traceback (most recent call last):
  File "C:\Program Files\IDA Pro 7.5 SP3\python\3\ida_idaapi.py", line 616, in IDAPython_ExecScript
    exec(code, g)
  File "C:/Program Files/IDA Pro 7.5 SP3/plugins/capa_explorer.py", line 9, in <module>
    from capa.ida.plugin import CapaExplorerPlugin
  File "C:\Python39\lib\site-packages\capa\ida\plugin\__init__.py", line 14, in <module>
    from capa.ida.plugin.form import CapaExplorerForm
  File "C:\Python39\lib\site-packages\capa\ida\plugin\form.py", line 18, in <module>
    import ida_settings
  File "C:\Python39\lib\site-packages\ida_settings\__init__.py", line 1, in <module>
    from .ida_settings import IDASettings, PermissionError
  File "C:\Python39\lib\site-packages\ida_settings\ida_settings.py", line 168, in <module>
    QtCore = import_qtcore()
  File "C:\Python39\lib\site-packages\ida_settings\ida_settings.py", line 141, in import_qtcore
    from PyQt5 import QtCore
ImportError: DLL load failed while importing sip: The specified module could not be found.
```

Running Python3.9.0 and IDA 7.5 SP3 here, when i try to manually import that from command prompt on my windows OS it works but the same fails in IDA. Ideas?

**Comment by mr-tz** [comment]
Can you double-check your IDA is using the correct Python where you setup capa?

**Comment by Ana06** [comment]
It seem this is helpful to solve this problem: https://github.com/joxeankoret/diaphora/issues/173

**Comment by williballenthin** [comment]
the above instructions seem to help with this bug. otherwise, we're not able to reproduce the issue. please reopen if the issue is encountered again.
