### ISSUE TITLE
Capa v3.0.1 No longer works on ELF files

### ISSUE THREAD

**Issue by JaryDev** [mandiant/capa#795]
### Description

Using capa v3.0.1 to analyse ELF binaries no longer works

### Steps to Reproduce

./capa elf_binary

**Expected behavior:**

Provides printout of capabilities to terminal. 

**Actual behavior:**
```
Traceback (most recent call last):
  File "main.py", line 1025, in <module>
  File "main.py", line 917, in main
  File "main.py", line 442, in get_extractor
  File "main.py", line 382, in get_workspace
  File "viv_utils/__init__.py", line 105, in getWorkspace
  File "vivisect/__init__.py", line 2742, in loadFromFile
  File "vivisect/base.py", line 197, in _snapInAnalysisModules
  File "vivisect/analysis/__init__.py", line 140, in addAnalysisModules
  File "vivisect/__init__.py", line 524, in addAnalysisModule
  File "vivisect/__init__.py", line 540, in loadModule
ModuleNotFoundError: No module named 'vivisect.analysis.elf.elfplt_late'
[3735] Failed to execute script main
```

### Versions

Standalone tool
capa v3.0.1-0-gf2082f3
Ubuntu 18.04.5 LTS (bionic) x86_64

### Additional Information

This is not an issue is in capa version 3.0.0

**Comment by mr-tz** [comment]
Ugh, nice find. Will fix this shortly. I suspect an issue with PyInstaller / vivisect hidden imports.

**Comment by williballenthin** [comment]
@JaryDev can you try the new standalone executables published here: https://github.com/mandiant/capa/releases/tag/v3.0.2

**Comment by JaryDev** [comment]
Hi @williballenthin, just tested it. Works great now. Thank you! :)
