### ISSUE TITLE
vivisect.exc.CorruptPeFile: PE: corrupt file: truncated section headers

### ISSUE THREAD

**Issue by mr-tz** [mandiant/capa#796]
For 0761142efbda6c4b1e801223de723578.dll_

```
failed to extract capabilities: query environment variable /home/runner/work/capa-rules/capa-rules/rules/../scripts/../tests/data/0761142efbda6c4b1e801223de723578.dll_ PE: corrupt file: truncated section headers
Traceback (most recent call last):
  File "/home/runner/work/capa-rules/capa-rules/rules/../scripts/lint.py", line 279, in check_rule
    capabilities = get_sample_capabilities(ctx, path)
  File "/home/runner/work/capa-rules/capa-rules/rules/../scripts/lint.py", line 234, in get_sample_capabilities
    extractor = capa.main.get_extractor(
  File "/home/runner/work/capa-rules/capa-rules/capa/main.py", line 442, in get_extractor
    vw = get_workspace(path, format, sigpaths)
  File "/home/runner/work/capa-rules/capa-rules/capa/main.py", line 382, in get_workspace
    vw = viv_utils.getWorkspace(path, analyze=False, should_save=False)
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/viv_utils/__init__.py", line 105, in getWorkspace
    vw.loadFromFile(fp)
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/vivisect/__init__.py", line 2737, in loadFromFile
    fname = mod.parseFile(self, filename=filename, baseaddr=baseaddr)
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/vivisect/parsers/pe.py", line 37, in parseFile
    return loadPeIntoWorkspace(vw, pe, filename=filename, baseaddr=baseaddr)
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/vivisect/parsers/pe.py", line 528, in loadPeIntoWorkspace
    pebytes = subpe.readAtOffset(0, subpe.getFileSize())
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/PE/carve.py", line 68, in getFileSize
    for sec in self.getSections():
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/PE/__init__.py", line 497, in getSections
    return self.sections
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/PE/__init__.py", line 1441, in __getattr__
    self.parseSections()
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/PE/__init__.py", line 728, in parseSections
    raise v_exc.CorruptPeFile("truncated section headers")
vivisect.exc.CorruptPeFile: PE: corrupt file: truncated section headers
```

solution proposed in https://github.com/vivisect/vivisect/pull/464

**Comment by williballenthin** [comment]
should be fixed due to upstream merging the PR

**Comment by mr-tz** [comment]
Yes, thanks!
