### ISSUE TITLE
Linux ELF Not Recognised

### ISSUE THREAD

**Issue by schrodyn** [mandiant/capa#867]
### Description
Testing capa with a basic Linux kernel module fails.

```
root@debian:~/src/git/linux_kernel_hacking/0_Basic_LKMs/0.0_Basic# ~/capa example.ko
loading : [8<]
ERROR:capa:--------------------------------------------------------------------------------
ERROR:capa: Input file does not appear to target a supported OS.
ERROR:capa:
ERROR:capa: capa currently only supports analyzing executables for some operating systems (including Windows and Linux).
ERROR:capa:--------------------------------------------------------------------------------
root@debian:~/src/git/linux_kernel_hacking/0_Basic_LKMs/0.0_Basic# file example.ko
example.ko: ELF 64-bit LSB relocatable, x86-64, version 1 (SYSV), BuildID[sha1]=dc941d6e3f77657bcbacf3d2d23c06b7a209e00d, not stripped
root@debian:~/src/git/linux_kernel_hacking/0_Basic_LKMs/0.0_Basic#
```

### Steps to Reproduce
Files tested are available on VT:

* [9f38a726c7c3d52efeabb041861cf9fac03949594fc81019309883713e01c1cc](https://www.virustotal.com/gui/file/9f38a726c7c3d52efeabb041861cf9fac03949594fc81019309883713e01c1cc)
* [82dae644c7a956a41d70097b7a749ca26fc6e04f0fa3186ee72955b2b5c550b6](https://www.virustotal.com/gui/file/82dae644c7a956a41d70097b7a749ca26fc6e04f0fa3186ee72955b2b5c550b6)

### Versions
capa v3.1.0-0-gc0851fc

### Additional Information
Input file is a simple compile of the example Linux kernel module from the following source code: https://github.com/xcellerator/linux_kernel_hacking/tree/master/0_Basic_LKMs/0.0_Basic Compiled on Debian.

```
root@debian:~/src/git/linux_kernel_hacking/0_Basic_LKMs/0.0_Basic# cat /etc/debian_version
11.2
```

**Comment by williballenthin** [comment]
```
❯ readelf -a 82dae644c7a956a41d70097b7a749ca26fc6e04f0fa3186ee72955b2b5c550b6
ELF Header:
  Magic:   7f 45 4c 46 02 01 01 00 00 00 00 00 00 00 00 00
  Class:                             ELF64
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              REL (Relocatable file)
  Machine:                           Advanced Micro Devices X86-64
  Version:                           0x1
  Entry point address:               0x0
  Start of program headers:          0 (bytes into file)
  Start of section headers:          2808 (bytes into file)
  Flags:                             0x0
  Size of this header:               64 (bytes)
  Size of program headers:           0 (bytes)
  Number of program headers:         0
  Size of section headers:           64 (bytes)
  Number of section headers:         25
  Section header string table index: 24

Section Headers:
  [Nr] Name              Type             Address           Offset
       Size              EntSize          Flags  Link  Info  Align
  [ 0]                   NULL             0000000000000000  00000000
       0000000000000000  0000000000000000           0     0     0
  [ 1] .note.gnu.build-i NOTE             0000000000000000  00000040
       0000000000000024  0000000000000000   A       0     0     4
  [ 2] .note.Linux       NOTE             0000000000000000  00000064
       0000000000000024  0000000000000000   A       0     0     4
  [ 3] .text             PROGBITS         0000000000000000  00000088
       0000000000000000  0000000000000000  AX       0     0     1
  [ 4] .init.text        PROGBITS         0000000000000000  00000088
       0000000000000014  0000000000000000  AX       0     0     1
  [ 5] .rela.init.text   RELA             0000000000000000  000008e0
       0000000000000048  0000000000000018   I      22     4     8
  [ 6] .exit.text        PROGBITS         0000000000000000  0000009c
       000000000000000c  0000000000000000  AX       0     0     1
  [ 7] .rela.exit.text   RELA             0000000000000000  00000928
       0000000000000030  0000000000000018   I      22     6     8
  [ 8] .rodata.str1.1    PROGBITS         0000000000000000  000000a8
       0000000000000024  0000000000000001 AMS       0     0     1
  [ 9] __mcount_loc      PROGBITS         0000000000000000  000000cc
       0000000000000008  0000000000000000   A       0     0     1
  [10] .rela__mcount_loc RELA             0000000000000000  00000958
       0000000000000018  0000000000000018   I      22     9     8
  [11] .modinfo          PROGBITS         0000000000000000  000000d4
       00000000000000b4  0000000000000000   A       0     0     1
  [12] .orc_unwind_ip    PROGBITS         0000000000000000  00000188
       0000000000000010  0000000000000000   A       0     0     1
  [13] .rela.orc_unwind_ RELA             0000000000000000  00000970
       0000000000000060  0000000000000018   I      22    12     8
  [14] .orc_unwind       PROGBITS         0000000000000000  00000198
       0000000000000018  0000000000000000   A       0     0     1
  [15] __versions        PROGBITS         0000000000000000  000001c0
       00000000000000c0  0000000000000000   A       0     0     32
  [16] .data             PROGBITS         0000000000000000  00000280
       0000000000000000  0000000000000000  WA       0     0     1
  [17] .gnu.linkonce.thi PROGBITS         0000000000000000  00000280
       00000000000003c0  0000000000000000  WA       0     0     64
  [18] .rela.gnu.linkonc RELA             0000000000000000  000009d0
       0000000000000030  0000000000000018   I      22    17     8
  [19] .bss              NOBITS           0000000000000000  00000640
       0000000000000000  0000000000000000  WA       0     0     1
  [20] .comment          PROGBITS         0000000000000000  00000640
       0000000000000050  0000000000000001  MS       0     0     1
  [21] .note.GNU-stack   PROGBITS         0000000000000000  00000690
       0000000000000000  0000000000000000           0     0     1
  [22] .symtab           SYMTAB           0000000000000000  00000690
       0000000000000210  0000000000000018          23    17     8
  [23] .strtab           STRTAB           0000000000000000  000008a0
       000000000000003c  0000000000000000           0     0     1
  [24] .shstrtab         STRTAB           0000000000000000  00000a00
       00000000000000f2  0000000000000000           0     0     1
Key to Flags:
  W (write), A (alloc), X (execute), M (merge), S (strings), I (info),
  L (link order), O (extra OS processing required), G (group), T (TLS),
  C (compressed), x (unknown), o (OS specific), E (exclude),
  l (large), p (processor specific)

There are no section groups in this file.

There are no program headers in this file.

There is no dynamic section in this file.

Relocation section '.rela.init.text' at offset 0x8e0 contains 3 entries:
  Offset          Info           Type           Sym. Value    Sym. Name + Addend
000000000001  001300000004 R_X86_64_PLT32    0000000000000000 __fentry__ - 4
000000000008  00030000000b R_X86_64_32S      0000000000000000 .rodata.str1.1 + 0
00000000000d  001500000004 R_X86_64_PLT32    0000000000000000 printk - 4

Relocation section '.rela.exit.text' at offset 0x928 contains 2 entries:
  Offset          Info           Type           Sym. Value    Sym. Name + Addend
000000000003  00030000000b R_X86_64_32S      0000000000000000 .rodata.str1.1 + 11
000000000008  001500000004 R_X86_64_PLT32    0000000000000000 printk - 4

Relocation section '.rela__mcount_loc' at offset 0x958 contains 1 entry:
  Offset          Info           Type           Sym. Value    Sym. Name + Addend
000000000000  000100000001 R_X86_64_64       0000000000000000 .init.text + 0

Relocation section '.rela.orc_unwind_ip' at offset 0x970 contains 4 entries:
  Offset          Info           Type           Sym. Value    Sym. Name + Addend
000000000000  000100000002 R_X86_64_PC32     0000000000000000 .init.text + 0
000000000004  000100000002 R_X86_64_PC32     0000000000000000 .init.text + 14
000000000008  000200000002 R_X86_64_PC32     0000000000000000 .exit.text + 0
00000000000c  000200000002 R_X86_64_PC32     0000000000000000 .exit.text + c

Relocation section '.rela.gnu.linkonce.this_module' at offset 0x9d0 contains 2 entries:
  Offset          Info           Type           Sym. Value    Sym. Name + Addend
000000000150  001400000001 R_X86_64_64       0000000000000000 init_module + 0
000000000380  001200000001 R_X86_64_64       0000000000000000 cleanup_module + 0

The decoding of unwind sections for machine type Advanced Micro Devices X86-64 is not currently supported.

Symbol table '.symtab' contains 22 entries:
   Num:    Value          Size Type    Bind   Vis      Ndx Name
     0: 0000000000000000     0 NOTYPE  LOCAL  DEFAULT  UND
     1: 0000000000000000     0 SECTION LOCAL  DEFAULT    4
     2: 0000000000000000     0 SECTION LOCAL  DEFAULT    6
     3: 0000000000000000     0 SECTION LOCAL  DEFAULT    8
     4: 0000000000000000     0 SECTION LOCAL  DEFAULT    1
     5: 0000000000000000     0 SECTION LOCAL  DEFAULT    2
     6: 0000000000000000     0 SECTION LOCAL  DEFAULT    3
     7: 0000000000000000     0 SECTION LOCAL  DEFAULT    9
     8: 0000000000000000     0 SECTION LOCAL  DEFAULT   11
     9: 0000000000000000     0 SECTION LOCAL  DEFAULT   12
    10: 0000000000000000     0 SECTION LOCAL  DEFAULT   14
    11: 0000000000000000     0 SECTION LOCAL  DEFAULT   15
    12: 0000000000000000     0 SECTION LOCAL  DEFAULT   16
    13: 0000000000000000     0 SECTION LOCAL  DEFAULT   17
    14: 0000000000000000     0 SECTION LOCAL  DEFAULT   19
    15: 0000000000000000     0 SECTION LOCAL  DEFAULT   20
    16: 0000000000000000     0 SECTION LOCAL  DEFAULT   21
    17: 0000000000000000   960 OBJECT  GLOBAL DEFAULT   17 __this_module
    18: 0000000000000000    12 FUNC    GLOBAL DEFAULT    6 cleanup_module
    19: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND __fentry__
    20: 0000000000000000    20 FUNC    GLOBAL DEFAULT    4 init_module
    21: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND printk

No version information found in this file.

Displaying notes found in: .note.gnu.build-id
  Owner                Data size        Description
  GNU                  0x00000014       NT_GNU_BUILD_ID (unique build ID bitstring)
    Build ID: dc941d6e3f77657bcbacf3d2d23c06b7a209e00d

Displaying notes found in: .note.Linux
  Owner                Data size        Description
  Linux                0x00000010       OPEN
   description data: 35 2e 31 30 2e 30 2d 31 30 2d 61 6d 64 36 34 00
```

**Comment by williballenthin** [comment]
the `.note.Linux` data decodes to: `5.10.0-10-amd64`

**Comment by williballenthin** [comment]
notably `file` doesn't detect this as for linux, either.

**Comment by williballenthin** [comment]
the note is not represented by a program header, only a section.

```
  Size of program headers:           0 (bytes)
  Number of program headers:         0
  Size of section headers:           64 (bytes)
  Number of section headers:         25
```

**Comment by williballenthin** [comment]
this ELF file also makes vivisect pretty unhappy:

```
❯ python -m capa.main ~/Downloads/82dae644c7a956a41d70097b7a749ca26fc6e04f0fa3186ee72955b2b5c550b6
loading : 100%|███████████████████████████| 658/658 [00:00<00:00, 2485.65 rules/s]
..  analyzing programINFO:Elf:self._parsePheaders
INFO:Elf:self._parseDynLinkInfo
INFO:Elf:self._parseSections
INFO:Elf:self._parseDynamicsFromSections
INFO:Elf:self._parseDynStrs
INFO:Elf:no dynamic string tableinfo found: DT_STRTAB: None  DT_STRSZ: None
INFO:Elf:self._parseDynSyms
INFO:Elf:self._parseDynRelocs
INFO:Elf:self._parseDynSymsFromSections
INFO:Elf:self._parseSectionSymbols
INFO:Elf:self._parseSectionRelocs
WARNING:Elf:_parseSectionRelocs: Reloc section differs from Dynamics: 0x8e0
INFO:Elf:section reloc: reloc: @0x1 4
INFO:Elf:section reloc: reloc: @0x8 11
INFO:Elf:section reloc: reloc: @0xd 4
WARNING:Elf:_parseSectionRelocs: Reloc section differs from Dynamics: 0x928
INFO:Elf:section reloc: reloc: @0x3 11
WARNING:Elf:_parseSectionRelocs: Reloc section differs from Dynamics: 0x958
INFO:Elf:section reloc: reloc: @0x0 1
WARNING:Elf:_parseSectionRelocs: Reloc section differs from Dynamics: 0x970
INFO:Elf:section reloc: reloc: @0x4 2
INFO:Elf:section reloc: reloc: @0xc 2
WARNING:Elf:_parseSectionRelocs: Reloc section differs from Dynamics: 0x9d0
INFO:Elf:section reloc: reloc: @0x150 1
INFO:Elf:section reloc: reloc: @0x380 1
INFO:Elf:done parsing ELF
INFO:vivisect:elf: no program headers found!
WARNING:vivisect.parsers.elf:unknown reloc type: 4  (at 0x1)
WARNING:vivisect.parsers.elf:00000000 (24) Elf64Reloca: reloc: @0x1 4
00000000 (08)   r_offset: 0x00000001 (1)
00000008 (08)   r_info: 0x1300000004 (81604378628)
00000010 (08)   r_addend: 0xfffffffffffffffc (18446744073709551612)

WARNING:vivisect.parsers.elf:unknown reloc type: 11  (at 0x8)
WARNING:vivisect.parsers.elf:00000000 (24) Elf64Reloca: reloc: @0x8 11
00000000 (08)   r_offset: 0x00000008 (8)
00000008 (08)   r_info: 0x30000000b (12884901899)
00000010 (08)   r_addend: 0x00000000 (0)

WARNING:vivisect.parsers.elf:unknown reloc type: 4  (at 0xd)
WARNING:vivisect.parsers.elf:00000000 (24) Elf64Reloca: reloc: @0xd 4
00000000 (08)   r_offset: 0x0000000d (13)
00000008 (08)   r_info: 0x1500000004 (90194313220)
00000010 (08)   r_addend: 0xfffffffffffffffc (18446744073709551612)

WARNING:vivisect.parsers.elf:unknown reloc type: 11  (at 0x3)
WARNING:vivisect.parsers.elf:00000000 (24) Elf64Reloca: reloc: @0x3 11
00000000 (08)   r_offset: 0x00000003 (3)
00000008 (08)   r_info: 0x30000000b (12884901899)
00000010 (08)   r_addend: 0x00000011 (17)

WARNING:vivisect.parsers.elf:unknown reloc type: 1  (at 0x0)
WARNING:vivisect.parsers.elf:00000000 (24) Elf64Reloca: reloc: @0x0 1
00000000 (08)   r_offset: 0x00000000 (0)
00000008 (08)   r_info: 0x100000001 (4294967297)
00000010 (08)   r_addend: 0x00000000 (0)

WARNING:vivisect.parsers.elf:unknown reloc type: 2  (at 0x4)
WARNING:vivisect.parsers.elf:00000000 (24) Elf64Reloca: reloc: @0x4 2
00000000 (08)   r_offset: 0x00000004 (4)
00000008 (08)   r_info: 0x100000002 (4294967298)
00000010 (08)   r_addend: 0x00000014 (20)

WARNING:vivisect.parsers.elf:unknown reloc type: 2  (at 0xc)
WARNING:vivisect.parsers.elf:00000000 (24) Elf64Reloca: reloc: @0xc 2
00000000 (08)   r_offset: 0x0000000c (12)
00000008 (08)   r_info: 0x200000002 (8589934594)
00000010 (08)   r_addend: 0x0000000c (12)

WARNING:vivisect.parsers.elf:unknown reloc type: 1  (at 0x150)
WARNING:vivisect.parsers.elf:00000000 (24) Elf64Reloca: reloc: @0x150 1
00000000 (08)   r_offset: 0x00000150 (336)
00000008 (08)   r_info: 0x1400000001 (85899345921)
00000010 (08)   r_addend: 0x00000000 (0)

WARNING:vivisect.parsers.elf:unknown reloc type: 1  (at 0x380)
WARNING:vivisect.parsers.elf:00000000 (24) Elf64Reloca: reloc: @0x380 1
00000000 (08)   r_offset: 0x00000380 (896)
00000008 (08)   r_info: 0x1200000001 (77309411329)
00000010 (08)   r_addend: 0x00000000 (0)

INFO:vivisect.parsers.elf:sva==0, using relocation name: 1: ''
INFO:vivisect.parsers.elf:sva==0, using relocation name: 1: ''
INFO:vivisect.parsers.elf:sva==0, using relocation name: 1: ''
INFO:vivisect.parsers.elf:sva==0, using relocation name: 1: ''
INFO:vivisect.parsers.elf:sva==0, using relocation name: 1: ''
INFO:vivisect.parsers.elf:sva==0, using relocation name: 1: ''
INFO:vivisect.parsers.elf:sva==0, using relocation name: 1: ''
INFO:vivisect.parsers.elf:sva==0, using relocation name: 1: ''
INFO:vivisect.parsers.elf:sva==0, using relocation name: 1: ''
INFO:vivisect.parsers.elf:sva==0, using relocation name: 1: ''
INFO:vivisect.parsers.elf:sva==0, using relocation name: 1: ''
INFO:vivisect.parsers.elf:sva==0, using relocation name: 1: ''
INFO:vivisect.parsers.elf:sva==0, using relocation name: 1: ''
INFO:vivisect.parsers.elf:sva==0, using relocation name: 1: ''
INFO:vivisect.parsers.elf:sva==0, using relocation name: 1: ''
INFO:vivisect.parsers.elf:sva==0, using relocation name: 1: ''
INFO:vivisect.parsers.elf:sva==0, using relocation name: 1: ''
INFO:vivisect:Failed to find file for 0x00000000 (__this_module) (and filelocal == True!)
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/user/code/capa-pub/capa/main.py", line 1095, in <module>
    sys.exit(main())
  File "/home/user/code/capa-pub/capa/main.py", line 986, in main
    extractor = get_extractor(
  File "/home/user/code/capa-pub/capa/main.py", line 463, in get_extractor
    vw = get_workspace(path, format, sigpaths)
  File "/home/user/code/capa-pub/capa/main.py", line 403, in get_workspace
    vw = viv_utils.getWorkspace(path, analyze=False, should_save=False)
  File "/home/user/code/viv-utils/viv_utils/__init__.py", line 106, in getWorkspace
    vw.loadFromFile(fp)
  File "/home/user/env/lib/python3.8/site-packages/vivisect-1.0.5-py3.8.egg/vivisect/__init__.py", line 2737, in loadFromFile
    fname = mod.parseFile(self, filename=filename, baseaddr=baseaddr)
  File "/home/user/env/lib/python3.8/site-packages/vivisect-1.0.5-py3.8.egg/vivisect/parsers/elf.py", line 31, in parseFile
    return loadElfIntoWorkspace(vw, elf, filename=filename, baseaddr=baseaddr)
  File "/home/user/env/lib/python3.8/site-packages/vivisect-1.0.5-py3.8.egg/vivisect/parsers/elf.py", line 531, in loadElfIntoWorkspace
    valu = vw.readMemoryPtr(sva)
  File "/home/user/env/lib/python3.8/site-packages/vivisect-1.0.5-py3.8.egg/envi/memory.py", line 187, in readMemoryPtr
    return self.readMemValue(va, self.imem_psize)
  File "/home/user/env/lib/python3.8/site-packages/vivisect-1.0.5-py3.8.egg/envi/memory.py", line 169, in readMemValue
    bytes = self.readMemory(addr, size)
  File "/home/user/env/lib/python3.8/site-packages/vivisect-1.0.5-py3.8.egg/envi/memory.py", line 539, in readMemory
    raise envi.SegmentationViolation(va)
envi.exc.SegmentationViolation: SegmentationViolation('Bad Memory Access: 0x0')
```
