### ISSUE TITLE
TypeError: %X format: an integer is required, not float

### ISSUE THREAD

**Issue by mr-tz** [mandiant/capa#983]
```
python scripts/show-features.py tests/data/1c444ebeba24dcba8628b7dfe5fec7c6.exe_ -f dotnet

insn: 0x000006a9: api(System.Windows.Forms.Control::SuspendLayout)
6.0
Traceback (most recent call last):
  File "scripts/show-features.py", line 231, in <module>
    sys.exit(main())
  File "scripts/show-features.py", line 154, in main
    print_features(functions, extractor)
  File "scripts/show-features.py", line 221, in print_features
    print("insn: 0x%08x: %s" % (va, feature))
  File "C:\Users\moritz.raabe\code\Exclusions\capa\capa\features\common.py", line 143, in __str__
    return "%s(%s)" % (self.name, self.get_value_str())
  File "C:\Users\moritz.raabe\code\Exclusions\capa\capa\features\insn.py", line 25, in get_value_str
    return capa.render.utils.hex(self.value)
  File "C:\Users\moritz.raabe\code\Exclusions\capa\capa\render\utils.py", line 29, in hex
    return "0x%X" % n
TypeError: %X format: an integer is required, not float

```

**Comment by williballenthin** [comment]
interesting, do we need a few feature for "float"? or do we put floats into the existing "number" feature?

**Comment by williballenthin** [comment]
in theory we could be extracting floats from native code today, but we just dont for no good reason except lack of interest.

**Comment by mike-hunhoff** [comment]
I vote we group `int` and `float` under `number` to avoid over complicating rule syntax.

**Comment by mike-hunhoff** [comment]
but unsure how/if this complicates the matching engine.

**Comment by williballenthin** [comment]
i dont think it will make matching hard, just a matter of keeping the types straight throughout the codebase. its a good opportunity to update our type annotations.
